server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_system?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath*:com/jxd/travel/dao/mapping/*.xml
  type-aliases-package: com.jxd.travel.model
##设置日志
logging:
  level:
    com.jxd.travel.dao: debug